GITHUB_BASE_URL: "https://api.github.com"
GITHUB_APP_ID: "344449"
GITHUB_APP_PRIVATE_KEY_PATH: "C:\\Users\\Stock\\certs\\refactoringjanitor1.2023-06-07.private-key.pem"
GITHUB_APP_WEBHOOK_SECRETS: "development"
